-- 100 INGREDIENTS
insert into ingredients (name) values ('Chicken breast');
insert into ingredients (name) values ('Ground beef');
insert into ingredients (name) values ('Salmon');
insert into ingredients (name) values ('Tofu');
insert into ingredients (name) values ('Eggs');
insert into ingredients (name) values ('Shrimp');
insert into ingredients (name) values ('Lentils');
insert into ingredients (name) values ('Chickpeas');
insert into ingredients (name) values ('Almonds');
insert into ingredients (name) values ('Greek yogurt');
insert into ingredients (name) values ('Spinach');
insert into ingredients (name) values ('Broccoli');
insert into ingredients (name) values ('Carrots');
insert into ingredients (name) values ('Bell peppers');
insert into ingredients (name) values ('Onions');
insert into ingredients (name) values ('Tomatoes');
insert into ingredients (name) values ('Garlic');
insert into ingredients (name) values ('Mushrooms');
insert into ingredients (name) values ('Zucchini');
insert into ingredients (name) values ('Cabbage');
insert into ingredients (name) values ('Bananas');
insert into ingredients (name) values ('Apples');
insert into ingredients (name) values ('Strawberries');
insert into ingredients (name) values ('Avocados');
insert into ingredients (name) values ('Blueberries');
insert into ingredients (name) values ('Lemons');
insert into ingredients (name) values ('Oranges');
insert into ingredients (name) values ('Pineapple');
insert into ingredients (name) values ('Mangoes');
insert into ingredients (name) values ('Grapes');
insert into ingredients (name) values ('Rice');
insert into ingredients (name) values ('Quinoa');
insert into ingredients (name) values ('Oats');
insert into ingredients (name) values ('Pasta');
insert into ingredients (name) values ('Bread');
insert into ingredients (name) values ('Cornmeal');
insert into ingredients (name) values ('Sweet potatoes');
insert into ingredients (name) values ('Potatoes');
insert into ingredients (name) values ('Barley');
insert into ingredients (name) values ('Couscous');
insert into ingredients (name) values ('Salt');
insert into ingredients (name) values ('Black pepper');
insert into ingredients (name) values ('Cumin');
insert into ingredients (name) values ('Cinnamon');
insert into ingredients (name) values ('Basil');
insert into ingredients (name) values ('Oregano');
insert into ingredients (name) values ('Paprika');
insert into ingredients (name) values ('Ginger');
insert into ingredients (name) values ('Turmeric');
insert into ingredients (name) values ('Chili powder');
insert into ingredients (name) values ('Honey');
insert into ingredients (name) values ('Maple syrup');
insert into ingredients (name) values ('Butter');
insert into ingredients (name) values ('Olive oil');
insert into ingredients (name) values ('Sunflower oil');
insert into ingredients (name) values ('Vinegar');
insert into ingredients (name) values ('Soy sauce');
insert into ingredients (name) values ('Mustard');
insert into ingredients (name) values ('Mayonnaise');
insert into ingredients (name) values ('Ketchup');
insert into ingredients (name) values ('Coconut milk');
insert into ingredients (name) values ('Heavy cream');
insert into ingredients (name) values ('Parmesan cheese');
insert into ingredients (name) values ('Cheddar cheese');
insert into ingredients (name) values ('Mozzarella cheese');
insert into ingredients (name) values ('Feta cheese');
insert into ingredients (name) values ('Brown sugar');
insert into ingredients (name) values ('White sugar');
insert into ingredients (name) values ('Nutmeg');
insert into ingredients (name) values ('Cardamom');
insert into ingredients (name) values ('Cloves');
insert into ingredients (name) values ('Bay leaves');
insert into ingredients (name) values ('Thyme');
insert into ingredients (name) values ('Rosemary');
insert into ingredients (name) values ('Coriander');
insert into ingredients (name) values ('Dill');
insert into ingredients (name) values ('Parsley');
insert into ingredients (name) values ('Chia seeds');
insert into ingredients (name) values ('Flaxseeds');
insert into ingredients (name) values ('Walnuts');
insert into ingredients (name) values ('Peanuts');
insert into ingredients (name) values ('Cashews');
insert into ingredients (name) values ('Pecans');
insert into ingredients (name) values ('Pistachios');
insert into ingredients (name) values ('Pumpkin seeds');
insert into ingredients (name) values ('Sesame seeds');
insert into ingredients (name) values ('Cocoa powder');
insert into ingredients (name) values ('Dark chocolate');
insert into ingredients (name) values ('White chocolate');
insert into ingredients (name) values ('Raisins');
insert into ingredients (name) values ('Dates');
insert into ingredients (name) values ('Figs');
insert into ingredients (name) values ('Prunes');
insert into ingredients (name) values ('Cranberries');
insert into ingredients (name) values ('Green tea');
insert into ingredients (name) values ('Black tea');
insert into ingredients (name) values ('Coffee beans');
insert into ingredients (name) values ('Coconut flour');
insert into ingredients (name) values ('Almond flour');
insert into ingredients (name) values ('Wheat flour');

-- 25 TAGS
insert into tags (name) values ('easy-recipes');
insert into tags (name) values ('healthy-meals');
insert into tags (name) values ('quick-dinners');
insert into tags (name) values ('vegetarian-recipes');
insert into tags (name) values ('vegan-meals');
insert into tags (name) values ('gluten-free');
insert into tags (name) values ('keto-friendly');
insert into tags (name) values ('low-carb');
insert into tags (name) values ('high-protein');
insert into tags (name) values ('dairy-free');
insert into tags (name) values ('one-pot-meals');
insert into tags (name) values ('budget-friendly');
insert into tags (name) values ('family-friendly');
insert into tags (name) values ('comfort-food');
insert into tags (name) values ('meal-prep');
insert into tags (name) values ('breakfast-ideas');
insert into tags (name) values ('lunch-recipes');
insert into tags (name) values ('dinner-inspiration');
insert into tags (name) values ('instant-pot');
insert into tags (name) values ('slow-cooker');
insert into tags (name) values ('air-fryer');
insert into tags (name) values ('grilling-recipes');
insert into tags (name) values ('pasta-dishes');
insert into tags (name) values ('dessert-lovers');
insert into tags (name) values ('homemade-cooking');

-- 100 Recipes
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Spaghetti Carbonara', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 158, 53, 'http://dummyimage.com/189x100.png/5fa2dd/ffffff', 715, 612, 714, 492, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Chicken Alfredo Pasta', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 74, 16, 'http://dummyimage.com/234x100.png/5fa2dd/ffffff', 390, 596, 710, 141, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Beef Stroganoff', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 49, 42, 'http://dummyimage.com/185x100.png/cc0000/ffffff', 535, 525, 90, 364, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Vegetable Stir-Fry', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 25, 109, 'http://dummyimage.com/234x100.png/cc0000/ffffff', 45, 145, 658, 898, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Shrimp Scampi', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 156, 93, 'http://dummyimage.com/226x100.png/dddddd/000000', 793, 711, 953, 76, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Chicken Parmesan', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 177, 117, 'http://dummyimage.com/161x100.png/5fa2dd/ffffff', 620, 474, 906, 364, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Grilled Salmon with Lemon Butter', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 50, 178, 'http://dummyimage.com/163x100.png/ff4444/ffffff', 569, 650, 430, 720, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Garlic Butter Steak', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 66, 67, 'http://dummyimage.com/221x100.png/5fa2dd/ffffff', 516, 170, 230, 234, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Creamy Mushroom Risotto', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 161, 7, 'http://dummyimage.com/104x100.png/dddddd/000000', 851, 150, 171, 385, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Baked Ziti', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 120, 68, 'http://dummyimage.com/173x100.png/5fa2dd/ffffff', 825, 85, 769, 296, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Classic Lasagna', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 26, 81, 'http://dummyimage.com/117x100.png/ff4444/ffffff', 300, 374, 953, 285, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Chicken Tikka Masala', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, 124, 'http://dummyimage.com/197x100.png/ff4444/ffffff', 746, 148, 452, 79, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('BBQ Pulled Pork Sandwiches', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 96, 151, 'http://dummyimage.com/172x100.png/5fa2dd/ffffff', 915, 178, 82, 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Stuffed Bell Peppers', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 41, 112, 'http://dummyimage.com/183x100.png/dddddd/000000', 150, 730, 17, 186, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Thai Green Curry', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 124, 90, 'http://dummyimage.com/158x100.png/5fa2dd/ffffff', 749, 327, 839, 846, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Homemade Margherita Pizza', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 101, 94, 'http://dummyimage.com/200x100.png/dddddd/000000', 46, 311, 822, 174, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Beef and Broccoli', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 147, 122, 'http://dummyimage.com/173x100.png/5fa2dd/ffffff', 569, 330, 602, 495, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Teriyaki Chicken', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 116, 20, 'http://dummyimage.com/221x100.png/cc0000/ffffff', 470, 528, 260, 208, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Shepherd’s Pie', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 51, 176, 'http://dummyimage.com/112x100.png/ff4444/ffffff', 111, 196, 143, 814, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Chicken Fajitas', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 39, 146, 'http://dummyimage.com/248x100.png/cc0000/ffffff', 246, 211, 529, 317, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Chili Con Carne', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 30, 72, 'http://dummyimage.com/226x100.png/dddddd/000000', 631, 593, 677, 338, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Greek Gyro Wraps', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 9, 116, 'http://dummyimage.com/223x100.png/5fa2dd/ffffff', 76, 117, 127, 211, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Tuna Casserole', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 127, 104, 'http://dummyimage.com/240x100.png/ff4444/ffffff', 866, 132, 693, 102, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Lemon Garlic Roasted Chicken', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 120, 163, 'http://dummyimage.com/250x100.png/ff4444/ffffff', 233, 907, 772, 901, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Shrimp and Grits', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 93, 44, 'http://dummyimage.com/185x100.png/dddddd/000000', 509, 391, 70, 199, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Butternut Squash Soup', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 15, 39, 'http://dummyimage.com/124x100.png/ff4444/ffffff', 649, 591, 197, 857, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Classic Caesar Salad', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 30, 7, 'http://dummyimage.com/160x100.png/5fa2dd/ffffff', 558, 62, 967, 325, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Avocado Toast with Poached Egg', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 22, 32, 'http://dummyimage.com/225x100.png/ff4444/ffffff', 832, 333, 660, 314, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Pancakes with Maple Syrup', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 6, 91, 'http://dummyimage.com/248x100.png/5fa2dd/ffffff', 855, 839, 438, 339, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('French Toast', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 59, 44, 'http://dummyimage.com/105x100.png/cc0000/ffffff', 692, 92, 358, 955, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Banana Bread', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 88, 139, 'http://dummyimage.com/164x100.png/5fa2dd/ffffff', 910, 88, 879, 277, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Blueberry Muffins', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 93, 101, 'http://dummyimage.com/134x100.png/dddddd/000000', 825, 213, 177, 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Apple Pie', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 27, 143, 'http://dummyimage.com/230x100.png/dddddd/000000', 794, 402, 188, 151, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Chocolate Chip Cookies', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 168, 150, 'http://dummyimage.com/177x100.png/cc0000/ffffff', 547, 514, 859, 755, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Brownie Sundae', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 109, 88, 'http://dummyimage.com/118x100.png/dddddd/000000', 850, 511, 865, 425, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Tiramisu', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 107, 38, 'http://dummyimage.com/121x100.png/5fa2dd/ffffff', 769, 776, 668, 305, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Cheesecake', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 128, 67, 'http://dummyimage.com/114x100.png/5fa2dd/ffffff', 948, 814, 424, 992, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Carrot Cake', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 123, 80, 'http://dummyimage.com/207x100.png/cc0000/ffffff', 111, 721, 561, 95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Pumpkin Pie', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 122, 37, 'http://dummyimage.com/247x100.png/ff4444/ffffff', 985, 37, 739, 783, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Smoothie Bowl', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 19, 174, 'http://dummyimage.com/211x100.png/dddddd/000000', 405, 834, 705, 377, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Guacamole and Chips', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 76, 87, 'http://dummyimage.com/145x100.png/cc0000/ffffff', 760, 653, 106, 186, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Hummus with Pita Bread', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 134, 52, 'http://dummyimage.com/120x100.png/ff4444/ffffff', 858, 380, 837, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Deviled Eggs', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 77, 121, 'http://dummyimage.com/136x100.png/5fa2dd/ffffff', 447, 122, 988, 559, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Stuffed Mushrooms', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 21, 93, 'http://dummyimage.com/176x100.png/cc0000/ffffff', 360, 866, 945, 409, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Caprese Salad', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 126, 94, 'http://dummyimage.com/219x100.png/dddddd/000000', 429, 9, 476, 243, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Bruschetta', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 72, 128, 'http://dummyimage.com/243x100.png/dddddd/000000', 244, 978, 183, 252, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Clam Chowder', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 101, 143, 'http://dummyimage.com/244x100.png/ff4444/ffffff', 366, 342, 972, 626, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Lobster Roll', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 147, 27, 'http://dummyimage.com/193x100.png/ff4444/ffffff', 934, 833, 809, 363, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Sushi Rolls', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 104, 27, 'http://dummyimage.com/214x100.png/cc0000/ffffff', 578, 141, 723, 452, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into recipes (title, description, preparing_time, cooking_time, image_url, calories, carbs, protein, fat, "createdAt", "updatedAt") values ('Pad Thai', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 22, 35, 'http://dummyimage.com/180x100.png/ff4444/ffffff', 131, 32, 512, 883, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 2 INSTRUCTIONS PER RECIPE

insert into instructions (recipe_id, step, title, description) values (1, 1, 'Boil pasta until al dente', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into instructions (recipe_id, step, title, description) values (1, 2, 'sauté onions and garlic', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into instructions (recipe_id, step, title, description) values (2, 1, 'marinate chicken for 30 minutes', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into instructions (recipe_id, step, title, description) values (2, 2, 'grill steak to desired doneness', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into instructions (recipe_id, step, title, description) values (3, 1, 'bake at 375°F for 25 minutes', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into instructions (recipe_id, step, title, description) values (3, 2, 'whisk eggs until fluffy', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into instructions (recipe_id, step, title, description) values (4, 1, 'mix dry and wet ingredients', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into instructions (recipe_id, step, title, description) values (4, 2, 'simmer sauce for 15 minutes', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into instructions (recipe_id, step, title, description) values (5, 1, 'chop vegetables finely', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into instructions (recipe_id, step, title, description) values (5, 2, 'season to taste', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into instructions (recipe_id, step, title, description) values (6, 1, 'blend until smooth', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into instructions (recipe_id, step, title, description) values (6, 2, 'knead dough until elastic', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into instructions (recipe_id, step, title, description) values (7, 1, 'let dough rise for an hour', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into instructions (recipe_id, step, title, description) values (7, 2, 'roast at 400°F until golden', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into instructions (recipe_id, step, title, description) values (8, 1, 'stir continuously to avoid burning', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into instructions (recipe_id, step, title, description) values (8, 2, 'melt butter in a pan', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into instructions (recipe_id, step, title, description) values (9, 1, 'preheat oven to 350°F', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into instructions (recipe_id, step, title, description) values (9, 2, 'dice tomatoes and onions', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into instructions (recipe_id, step, title, description) values (10, 1, 'coat evenly with breadcrumbs', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into instructions (recipe_id, step, title, description) values (10, 2, 'drizzle with olive oil', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');
insert into instructions (recipe_id, step, title, description) values (11, 1, 'mix well and refrigerate', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into instructions (recipe_id, step, title, description) values (11, 2, 'fold gently to keep fluffy', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into instructions (recipe_id, step, title, description) values (12, 1, 'spread evenly in a baking dish', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into instructions (recipe_id, step, title, description) values (12, 2, 'sear on high heat for 2 minutes', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into instructions (recipe_id, step, title, description) values (13, 1, 'let meat rest before slicing', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into instructions (recipe_id, step, title, description) values (13, 2, 'toss salad with dressing', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into instructions (recipe_id, step, title, description) values (14, 1, 'zest lemon for extra flavor', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into instructions (recipe_id, step, title, description) values (14, 2, 'mash until creamy', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into instructions (recipe_id, step, title, description) values (15, 1, 'grate cheese finely', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into instructions (recipe_id, step, title, description) values (15, 2, 'pour batter evenly into pan', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into instructions (recipe_id, step, title, description) values (16, 1, 'steam for 10 minutes', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into instructions (recipe_id, step, title, description) values (16, 2, 'glaze with honey before serving', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into instructions (recipe_id, step, title, description) values (17, 1, 'garnish with fresh herbs', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into instructions (recipe_id, step, title, description) values (17, 2, 'chill for at least an hour', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into instructions (recipe_id, step, title, description) values (18, 1, 'caramelize onions slowly', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into instructions (recipe_id, step, title, description) values (18, 2, 'pulse in a food processor', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into instructions (recipe_id, step, title, description) values (19, 1, 'layer ingredients neatly', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into instructions (recipe_id, step, title, description) values (19, 2, 'coat with sauce before baking', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into instructions (recipe_id, step, title, description) values (20, 1, 'beat until stiff peaks form', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into instructions (recipe_id, step, title, description) values (20, 2, 'broil for extra crispiness', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into instructions (recipe_id, step, title, description) values (21, 1, 'infuse with spices for more flavor', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into instructions (recipe_id, step, title, description) values (21, 2, 'press firmly into a baking tray', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into instructions (recipe_id, step, title, description) values (22, 1, 'soak overnight for best results', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into instructions (recipe_id, step, title, description) values (22, 2, 'baste frequently while roasting', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into instructions (recipe_id, step, title, description) values (23, 1, 'wrap tightly in foil', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into instructions (recipe_id, step, title, description) values (23, 2, 'dust with powdered sugar', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');
insert into instructions (recipe_id, step, title, description) values (24, 1, 'whisk continuously for a smooth texture', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into instructions (recipe_id, step, title, description) values (24, 2, 'skewer and grill until charred', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into instructions (recipe_id, step, title, description) values (25, 1, 'crumble topping over dessert', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into instructions (recipe_id, step, title, description) values (25, 2, 'strain before serving', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');

-- RecipeIngredients 

insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (16, 82, 337, 'g');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (5, 54, 372, 'g');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (19, 6, 210, 'mg');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (22, 29, 332, 'quart');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (12, 72, 381, 'dash');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (21, 38, 41, 'l');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (15, 14, 287, 'quart');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (8, 16, 338, 'kg');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (10, 11, 140, 'oz');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (25, 80, 320, 'ml');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (5, 2, 337, 'oz');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (20, 45, 237, 'g');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (15, 81, 59, 'fl oz');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (11, 45, 90, 'oz');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (19, 16, 16, 'dash');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (5, 69, 159, 'mg');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (24, 5, 349, 'pint');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (13, 30, 2, 'gallon');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (13, 7, 422, 'lb');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (11, 44, 349, 'cup');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (6, 19, 366, 'dash');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (17, 47, 257, 'tbsp');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (11, 17, 351, 'ml');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (4, 34, 392, 'mg');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (1, 46, 63, 'oz');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (10, 81, 15, 'pint');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (8, 92, 139, 'cup');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (16, 26, 262, 'tbsp');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (21, 35, 72, 'cup');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (11, 2, 206, 'quart');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (18, 71, 383, 'kg');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (3, 92, 437, 'kg');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (13, 60, 89, 'lb');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (7, 47, 96, 'tbsp');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (19, 78, 205, 'lb');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (10, 20, 325, 'lb');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (15, 51, 162, 'gallon');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (13, 75, 40, 'tbsp');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (7, 11, 275, 'cup');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (8, 3, 232, 'tsp');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (18, 72, 257, 'dash');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (19, 7, 54, 'tsp');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (24, 91, 211, 'mg');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (12, 30, 92, 'lb');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (5, 28, 25, 'cup');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (19, 96, 306, 'pint');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (9, 66, 376, 'pint');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (24, 43, 329, 'fl oz');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (9, 15, 317, 'g');
insert into recipes_ingredients (recipe_id, ingredient_id, quantity, measurement) values (19, 45, 394, 'gallon');

-- recipeTags

insert into recipes_tags (recipe_id, tag_id) values (14, 19);
insert into recipes_tags (recipe_id, tag_id) values (7, 23);
insert into recipes_tags (recipe_id, tag_id) values (24, 14);
insert into recipes_tags (recipe_id, tag_id) values (5, 2);
insert into recipes_tags (recipe_id, tag_id) values (25, 10);
insert into recipes_tags (recipe_id, tag_id) values (12, 3);
insert into recipes_tags (recipe_id, tag_id) values (22, 11);
insert into recipes_tags (recipe_id, tag_id) values (19, 3);
insert into recipes_tags (recipe_id, tag_id) values (20, 8);
insert into recipes_tags (recipe_id, tag_id) values (22, 14);
insert into recipes_tags (recipe_id, tag_id) values (10, 3);
insert into recipes_tags (recipe_id, tag_id) values (18, 9);
insert into recipes_tags (recipe_id, tag_id) values (18, 6);
insert into recipes_tags (recipe_id, tag_id) values (4, 10);
insert into recipes_tags (recipe_id, tag_id) values (9, 18);
insert into recipes_tags (recipe_id, tag_id) values (5, 4);
insert into recipes_tags (recipe_id, tag_id) values (10, 2);
insert into recipes_tags (recipe_id, tag_id) values (18, 8);
insert into recipes_tags (recipe_id, tag_id) values (7, 16);
insert into recipes_tags (recipe_id, tag_id) values (24, 22);
insert into recipes_tags (recipe_id, tag_id) values (5, 3);
insert into recipes_tags (recipe_id, tag_id) values (24, 4);
insert into recipes_tags (recipe_id, tag_id) values (9, 13);
insert into recipes_tags (recipe_id, tag_id) values (13, 3);
insert into recipes_tags (recipe_id, tag_id) values (6, 13);
insert into recipes_tags (recipe_id, tag_id) values (23, 22);
insert into recipes_tags (recipe_id, tag_id) values (8, 24);
insert into recipes_tags (recipe_id, tag_id) values (1, 4);
insert into recipes_tags (recipe_id, tag_id) values (18, 7);
insert into recipes_tags (recipe_id, tag_id) values (10, 8);
insert into recipes_tags (recipe_id, tag_id) values (6, 25);
insert into recipes_tags (recipe_id, tag_id) values (7, 12);
insert into recipes_tags (recipe_id, tag_id) values (8, 7);
insert into recipes_tags (recipe_id, tag_id) values (20, 4);
insert into recipes_tags (recipe_id, tag_id) values (22, 12);
insert into recipes_tags (recipe_id, tag_id) values (17, 19);
insert into recipes_tags (recipe_id, tag_id) values (12, 24);
insert into recipes_tags (recipe_id, tag_id) values (7, 17);
insert into recipes_tags (recipe_id, tag_id) values (22, 22);
insert into recipes_tags (recipe_id, tag_id) values (13, 23);
insert into recipes_tags (recipe_id, tag_id) values (14, 2);
insert into recipes_tags (recipe_id, tag_id) values (16, 19);
insert into recipes_tags (recipe_id, tag_id) values (21, 19);
insert into recipes_tags (recipe_id, tag_id) values (25, 25);
insert into recipes_tags (recipe_id, tag_id) values (9, 20);
insert into recipes_tags (recipe_id, tag_id) values (4, 11);
insert into recipes_tags (recipe_id, tag_id) values (17, 16);
insert into recipes_tags (recipe_id, tag_id) values (7, 9);
insert into recipes_tags (recipe_id, tag_id) values (12, 17);
insert into recipes_tags (recipe_id, tag_id) values (7, 8);